### PR TITLE
📦 Removed hardcoded values of add in the single and double fields

### PR DESCRIPTION
**Pull request by YoramGondwe**
#16 
Allowed for dynamic button descriptions

### CODE REVIEW

**Comment by OlivierJM** [comment]
@YoramGondwe can you provide a simple screenshot of how this looks

**Comment by YoramGondwe** [comment]
This is the screenshot of my changes
image

**Comment by OlivierJM** [comment]
@YoramGondwe the issue with this is that it doesn't make the button look like an action button, a button with "fruits" does not tell a user what that button does.

**Comment by YoramGondwe** [comment]
@OlivierJM This is to give the users the ability to give the action button their own descriptive words we can adjust the the example to give more context but otherwise it should be fine

**Comment by YoramGondwe** [comment]
image
I have made changes to the labels

**Comment by OlivierJM** [comment]
@YoramGondwe I reviewed this once again and as I said earlier, `{label || 'add Item'}` this won't be ideal, label should always be provided, and the label is not meant to be an actionable, it is a short description of items user is seeing. 

What I would propose is this, we provide a new prop just for buttons, in the next versions this will be a react node that can also accept external icons then we provide it with default data that can be used. 


```
DoubleField.defaultProps = {
  actionButtons: {
    add: 'Add',
    remove: 'Remove'
  }
} 
```
and it can be used this way 

```
      <button data-testid='add_field' onClick={handleAddField}>
        {actionButtons.add}
      </button>
```

The signature can look like this 

```
  actionButtons: PropTypes.shape({
    add: PropTypes.string,
    remove: PropTypes.string
  })
```
This way the user can provide whatever action button title they prefer which doesn't have to be the same as the data label.

**Comment by YoramGondwe** [comment]
> @YoramGondwe I reviewed this once again and as I said earlier, `{label || 'add Item'}` this won't be ideal, label should always be provided, and the label is not meant to be an actionable, it is a short description of items user is seeing.
> 
> What I would propose is this, we provide a new prop just for buttons, in the next versions this will be a react node that can also accept external icons then we provide it with default data that can be used.
> 
> ```
> DoubleField.defaultProps = {
>   actionButtons: {
>     add: 'Add',
>     remove: 'Remove'
>   }
> } 
> ```
> 
> and it can be used this way
> 
> ```
>       <button data-testid='add_field' onClick={handleAddField}>
>         {actionButtons.add}
>       </button>
> ```
> 
> The signature can look like this
> 
> ```
>   actionButtons: PropTypes.shape({
>     add: PropTypes.string,
>     remove: PropTypes.string
>   })
> ```
> 
> This way the user can provide whatever action button title they prefer which doesn't have to be the same as the data label.

Thanks I will work on your suggestion and make a push

**Pull request closed without merging**
