### PR TITLE
added styles using styled-components

### PR DESCRIPTION
**Pull request by NatashaChuza**
Added styling to the components using styled components, it's not customizable yet

### CODE REVIEW

**Comment by OlivierJM** [comment]
thanks a lot for the changes @NatashaChuza I will take a look at this.

**Review by OlivierJM — COMMENTED** [review]
Hi @NatashaChuza I checked this out and made some updates on types, It looks pretty great. 
I am thinking we push this to a v2 branch until we can have a way of toggling styles in case some users would prefer a basic look or a way to allow them to use their own themes. 
I like how it looks

**Comment by OlivierJM** [comment]
merging this to v2 branch.

**Comment by NatashaChuza** [comment]
> Hi @NatashaChuza I checked this out and made some updates on types, It looks pretty great.
> I am thinking we push this to a v2 branch until we can have a way of toggling styles in case some users would prefer a basic look or a way to allow them to use their own themes.
> I like how it looks

Hi Olivier, sorry I've been a little busy. That's a good idea. I'll try to make the styles more customizable this weekend.

**Comment by NatashaChuza** [comment]
> merging this to v2 branch.

Cool. Sorry about the late reply.

**Comment by OlivierJM** [comment]
> > Hi @NatashaChuza I checked this out and made some updates on types, It looks pretty great.
> > I am thinking we push this to a v2 branch until we can have a way of toggling styles in case some users would prefer a basic look or a way to allow them to use their own themes.
> > I like how it looks
> 
> Hi Olivier, sorry I've been a little busy. That's a good idea. I'll try to make the styles more customizable this weekend.

Thanks a lot Natasha

**Pull request merged**
